kind: PersistentVolume
apiVersion: v1
metadata:
  name: actuator-pv
  namespace: actuator-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/actuators